<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es">
  <head>
    <title>Registro de un nuevo producto</title>
  </head>
<body>
	<h2>Registra un producto nuevo en el sistema:</h2>
	<form action="index.php" method="POST" enctype="multipart/form-data">
	nombre<br><input type="text" name="nombre" value="Pon aqui el nombre del producto"/><br>
	categoria<br><input type="text" name="categoria" value="Pon aqui la categoria del producto"/><br>
	descripcion<br><input type="text" name="descripcion" value="Pon aqui la categoria del producto"/><br>
	precio<br><input type="text" name="precio" value="Pon aqui el precio del producto"/><br>
	cantidad<br><input type="text" name="cantidad" value="Pon aqui la cantidad del producto"/><br>
	foto<br><input type="file" name="avatar" value="Sube foto"/><br>
	<input type="submit" name="register" value="REGISTRO"/>
</form>
</body>
</html>