<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es">
  <head>
    <title>Login de usuario</title>
  </head>
 <body>
<h4>Inicia sesión:</h4>
<form action="index.php" method="POST">
<input type="text" name="userName" value="Pon aqui tu nombre de usuario"/>
<input type="password" name="password"/>
<input type="submit" value="LOG IN"/>
</form>
</body>
</html>