<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es">
  <head>
    <title>Registro de usuario</title>
  </head>
<body>
	<h4>Registrate:</h4>
	<form action="index.php" method="POST" enctype="multipart/form-data">
	nombre:<input type="text" name="userName" value="nombre"/><br>
	contrasegna<input type="password" name="password"/><br>
	direccion<input type="text" name="direccion" value="direccion"/><br>
	mail<input type="text" name="correo" value="correo"/><br>
	telefono<input type="text" name="telefono" value="telefono"/><br>
	<input type="submit" name="registerP" value="REGISTRO"/>
	<br>
	</form>
</body>
</html>
