<?php
//manejador de vistas en funcion del logeo y de las acciones del usuario.
	if(!isset($_SESSION['user'])){
		require("Views/form_loginView.phtml");
		require("Views/form_newPersona.phtml");
		require("Views/productosView.phtml");
	}else {
		if(isset($_GET['producto'])){
			require("Views/productoView.phtml");
		}else if(isset($_SESSION['user'])&& $_SESSION['user']->getRol()==1){
			require("Views/productosView.phtml");
			require("Views/form_newProducto.phtml");
			require("Views/usuariosView.phtml");
		}else{
			require("Views/productosView.phtml");
		}
	}
?>